// Package managementclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package managementclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	externalRef0 "github.com/hatchet-dev/hatchet/api/v1/server/oas/gen"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
	CustomAuthScopes = "customAuth.Scopes"
)

// Defines values for ManagementTokenDuration.
const (
	N30d ManagementTokenDuration = "30d"
	N60d ManagementTokenDuration = "60d"
	N90d ManagementTokenDuration = "90d"
)

// Defines values for OrganizationInviteStatus.
const (
	ACCEPTED OrganizationInviteStatus = "ACCEPTED"
	PENDING  OrganizationInviteStatus = "PENDING"
	REJECTED OrganizationInviteStatus = "REJECTED"
)

// Defines values for OrganizationMemberRoleType.
const (
	OWNER OrganizationMemberRoleType = "OWNER"
)

// Defines values for TenantStatus.
const (
	Active   TenantStatus = "active"
	Archived TenantStatus = "archived"
)

// APIError defines model for APIError.
type APIError = externalRef0.APIError

// APIResourceMeta defines model for APIResourceMeta.
type APIResourceMeta = externalRef0.APIResourceMeta

// APITokenList defines model for APITokenList.
type APITokenList = externalRef0.ListAPITokensResponse

// CreateManagementTokenRequest defines model for CreateManagementTokenRequest.
type CreateManagementTokenRequest struct {
	Duration *ManagementTokenDuration `json:"duration,omitempty"`

	// Name The name of the management token.
	Name string `json:"name"`
}

// CreateManagementTokenResponse defines model for CreateManagementTokenResponse.
type CreateManagementTokenResponse struct {
	// Token The token of the management token.
	Token string `json:"token"`
}

// CreateNewTenantForOrganizationRequest defines model for CreateNewTenantForOrganizationRequest.
type CreateNewTenantForOrganizationRequest struct {
	// Name The name of the tenant.
	Name string `json:"name"`

	// Slug The slug of the tenant.
	Slug string `json:"slug"`
}

// CreateOrganizationInviteRequest defines model for CreateOrganizationInviteRequest.
type CreateOrganizationInviteRequest struct {
	// InviteeEmail The email of the invitee
	InviteeEmail openapi_types.Email        `json:"inviteeEmail"`
	Role         OrganizationMemberRoleType `json:"role"`
}

// CreateTenantAPITokenRequest defines model for CreateTenantAPITokenRequest.
type CreateTenantAPITokenRequest = externalRef0.CreateAPITokenRequest

// CreateTenantAPITokenResponse defines model for CreateTenantAPITokenResponse.
type CreateTenantAPITokenResponse = externalRef0.CreateAPITokenResponse

// ManagementTokenDuration defines model for ManagementTokenDuration.
type ManagementTokenDuration string

// Organization defines model for Organization.
type Organization struct {
	Members  *[]OrganizationMember `json:"members,omitempty"`
	Metadata APIResourceMeta       `json:"metadata"`

	// Name Name of the organization
	Name    string                `json:"name"`
	Tenants *[]OrganizationTenant `json:"tenants,omitempty"`
}

// OrganizationInvite defines model for OrganizationInvite.
type OrganizationInvite struct {
	// Expires The timestamp at which the invite expires
	Expires time.Time `json:"expires"`

	// InviteeEmail The email of the invitee
	InviteeEmail openapi_types.Email `json:"inviteeEmail"`

	// InviterEmail The email of the inviter
	InviterEmail openapi_types.Email `json:"inviterEmail"`
	Metadata     APIResourceMeta     `json:"metadata"`

	// OrganizationId The ID of the organization
	OrganizationId openapi_types.UUID         `json:"organizationId"`
	Role           OrganizationMemberRoleType `json:"role"`
	Status         OrganizationInviteStatus   `json:"status"`
}

// OrganizationInviteList defines model for OrganizationInviteList.
type OrganizationInviteList struct {
	Rows []OrganizationInvite `json:"rows"`
}

// OrganizationInviteStatus defines model for OrganizationInviteStatus.
type OrganizationInviteStatus string

// OrganizationMember defines model for OrganizationMember.
type OrganizationMember struct {
	// Email Email of the user
	Email    openapi_types.Email        `json:"email"`
	Metadata APIResourceMeta            `json:"metadata"`
	Role     OrganizationMemberRoleType `json:"role"`
}

// OrganizationMemberRoleType defines model for OrganizationMemberRoleType.
type OrganizationMemberRoleType string

// OrganizationTenant defines model for OrganizationTenant.
type OrganizationTenant struct {
	// ArchivedAt The timestamp at which the tenant was archived
	ArchivedAt *time.Time `json:"archivedAt,omitempty"`

	// Id ID of the tenant
	Id     openapi_types.UUID `json:"id"`
	Status TenantStatus       `json:"status"`
}

// RemoveOrganizationMembersRequest defines model for RemoveOrganizationMembersRequest.
type RemoveOrganizationMembersRequest struct {
	// Emails Array of user emails to remove from the organization
	Emails []openapi_types.Email `json:"emails"`
}

// TenantStatus defines model for TenantStatus.
type TenantStatus string

// OrganizationMemberDeleteJSONRequestBody defines body for OrganizationMemberDelete for application/json ContentType.
type OrganizationMemberDeleteJSONRequestBody = RemoveOrganizationMembersRequest

// OrganizationTenantCreateApiTokenJSONRequestBody defines body for OrganizationTenantCreateApiToken for application/json ContentType.
type OrganizationTenantCreateApiTokenJSONRequestBody = CreateTenantAPITokenRequest

// OrganizationInviteCreateJSONRequestBody defines body for OrganizationInviteCreate for application/json ContentType.
type OrganizationInviteCreateJSONRequestBody = CreateOrganizationInviteRequest

// ManagementTokenCreateJSONRequestBody defines body for ManagementTokenCreate for application/json ContentType.
type ManagementTokenCreateJSONRequestBody = CreateManagementTokenRequest

// OrganizationCreateTenantJSONRequestBody defines body for OrganizationCreateTenant for application/json ContentType.
type OrganizationCreateTenantJSONRequestBody = CreateNewTenantForOrganizationRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// OrganizationMemberDeleteWithBody request with any body
	OrganizationMemberDeleteWithBody(ctx context.Context, organizationMember openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	OrganizationMemberDelete(ctx context.Context, organizationMember openapi_types.UUID, body OrganizationMemberDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationTenantDelete request
	OrganizationTenantDelete(ctx context.Context, organizationTenant openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationTenantListApiTokens request
	OrganizationTenantListApiTokens(ctx context.Context, organizationTenant openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationTenantCreateApiTokenWithBody request with any body
	OrganizationTenantCreateApiTokenWithBody(ctx context.Context, organizationTenant openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	OrganizationTenantCreateApiToken(ctx context.Context, organizationTenant openapi_types.UUID, body OrganizationTenantCreateApiTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationTenantDeleteApiToken request
	OrganizationTenantDeleteApiToken(ctx context.Context, organizationTenant openapi_types.UUID, apiToken openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationGet request
	OrganizationGet(ctx context.Context, organization openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationInviteList request
	OrganizationInviteList(ctx context.Context, organization openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationInviteCreateWithBody request with any body
	OrganizationInviteCreateWithBody(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	OrganizationInviteCreate(ctx context.Context, organization openapi_types.UUID, body OrganizationInviteCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ManagementTokenCreateWithBody request with any body
	ManagementTokenCreateWithBody(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ManagementTokenCreate(ctx context.Context, organization openapi_types.UUID, body ManagementTokenCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationCreateTenantWithBody request with any body
	OrganizationCreateTenantWithBody(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	OrganizationCreateTenant(ctx context.Context, organization openapi_types.UUID, body OrganizationCreateTenantJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) OrganizationMemberDeleteWithBody(ctx context.Context, organizationMember openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationMemberDeleteRequestWithBody(c.Server, organizationMember, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationMemberDelete(ctx context.Context, organizationMember openapi_types.UUID, body OrganizationMemberDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationMemberDeleteRequest(c.Server, organizationMember, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationTenantDelete(ctx context.Context, organizationTenant openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationTenantDeleteRequest(c.Server, organizationTenant)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationTenantListApiTokens(ctx context.Context, organizationTenant openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationTenantListApiTokensRequest(c.Server, organizationTenant)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationTenantCreateApiTokenWithBody(ctx context.Context, organizationTenant openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationTenantCreateApiTokenRequestWithBody(c.Server, organizationTenant, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationTenantCreateApiToken(ctx context.Context, organizationTenant openapi_types.UUID, body OrganizationTenantCreateApiTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationTenantCreateApiTokenRequest(c.Server, organizationTenant, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationTenantDeleteApiToken(ctx context.Context, organizationTenant openapi_types.UUID, apiToken openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationTenantDeleteApiTokenRequest(c.Server, organizationTenant, apiToken)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationGet(ctx context.Context, organization openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationGetRequest(c.Server, organization)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationInviteList(ctx context.Context, organization openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationInviteListRequest(c.Server, organization)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationInviteCreateWithBody(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationInviteCreateRequestWithBody(c.Server, organization, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationInviteCreate(ctx context.Context, organization openapi_types.UUID, body OrganizationInviteCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationInviteCreateRequest(c.Server, organization, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ManagementTokenCreateWithBody(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewManagementTokenCreateRequestWithBody(c.Server, organization, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ManagementTokenCreate(ctx context.Context, organization openapi_types.UUID, body ManagementTokenCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewManagementTokenCreateRequest(c.Server, organization, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationCreateTenantWithBody(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationCreateTenantRequestWithBody(c.Server, organization, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationCreateTenant(ctx context.Context, organization openapi_types.UUID, body OrganizationCreateTenantJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationCreateTenantRequest(c.Server, organization, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewOrganizationMemberDeleteRequest calls the generic OrganizationMemberDelete builder with application/json body
func NewOrganizationMemberDeleteRequest(server string, organizationMember openapi_types.UUID, body OrganizationMemberDeleteJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewOrganizationMemberDeleteRequestWithBody(server, organizationMember, "application/json", bodyReader)
}

// NewOrganizationMemberDeleteRequestWithBody generates requests for OrganizationMemberDelete with any type of body
func NewOrganizationMemberDeleteRequestWithBody(server string, organizationMember openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization-member", runtime.ParamLocationPath, organizationMember)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organization-members/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewOrganizationTenantDeleteRequest generates requests for OrganizationTenantDelete
func NewOrganizationTenantDeleteRequest(server string, organizationTenant openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization-tenant", runtime.ParamLocationPath, organizationTenant)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organization-tenants/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOrganizationTenantListApiTokensRequest generates requests for OrganizationTenantListApiTokens
func NewOrganizationTenantListApiTokensRequest(server string, organizationTenant openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization-tenant", runtime.ParamLocationPath, organizationTenant)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organization-tenants/%s/api-tokens", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOrganizationTenantCreateApiTokenRequest calls the generic OrganizationTenantCreateApiToken builder with application/json body
func NewOrganizationTenantCreateApiTokenRequest(server string, organizationTenant openapi_types.UUID, body OrganizationTenantCreateApiTokenJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewOrganizationTenantCreateApiTokenRequestWithBody(server, organizationTenant, "application/json", bodyReader)
}

// NewOrganizationTenantCreateApiTokenRequestWithBody generates requests for OrganizationTenantCreateApiToken with any type of body
func NewOrganizationTenantCreateApiTokenRequestWithBody(server string, organizationTenant openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization-tenant", runtime.ParamLocationPath, organizationTenant)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organization-tenants/%s/api-tokens", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewOrganizationTenantDeleteApiTokenRequest generates requests for OrganizationTenantDeleteApiToken
func NewOrganizationTenantDeleteApiTokenRequest(server string, organizationTenant openapi_types.UUID, apiToken openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization-tenant", runtime.ParamLocationPath, organizationTenant)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "api-token", runtime.ParamLocationPath, apiToken)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organization-tenants/%s/api-tokens/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOrganizationGetRequest generates requests for OrganizationGet
func NewOrganizationGetRequest(server string, organization openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization", runtime.ParamLocationPath, organization)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organizations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOrganizationInviteListRequest generates requests for OrganizationInviteList
func NewOrganizationInviteListRequest(server string, organization openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization", runtime.ParamLocationPath, organization)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organizations/%s/invites", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOrganizationInviteCreateRequest calls the generic OrganizationInviteCreate builder with application/json body
func NewOrganizationInviteCreateRequest(server string, organization openapi_types.UUID, body OrganizationInviteCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewOrganizationInviteCreateRequestWithBody(server, organization, "application/json", bodyReader)
}

// NewOrganizationInviteCreateRequestWithBody generates requests for OrganizationInviteCreate with any type of body
func NewOrganizationInviteCreateRequestWithBody(server string, organization openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization", runtime.ParamLocationPath, organization)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organizations/%s/invites", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewManagementTokenCreateRequest calls the generic ManagementTokenCreate builder with application/json body
func NewManagementTokenCreateRequest(server string, organization openapi_types.UUID, body ManagementTokenCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewManagementTokenCreateRequestWithBody(server, organization, "application/json", bodyReader)
}

// NewManagementTokenCreateRequestWithBody generates requests for ManagementTokenCreate with any type of body
func NewManagementTokenCreateRequestWithBody(server string, organization openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization", runtime.ParamLocationPath, organization)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organizations/%s/management-tokens", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewOrganizationCreateTenantRequest calls the generic OrganizationCreateTenant builder with application/json body
func NewOrganizationCreateTenantRequest(server string, organization openapi_types.UUID, body OrganizationCreateTenantJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewOrganizationCreateTenantRequestWithBody(server, organization, "application/json", bodyReader)
}

// NewOrganizationCreateTenantRequestWithBody generates requests for OrganizationCreateTenant with any type of body
func NewOrganizationCreateTenantRequestWithBody(server string, organization openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization", runtime.ParamLocationPath, organization)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organizations/%s/tenants", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// OrganizationMemberDeleteWithBodyWithResponse request with any body
	OrganizationMemberDeleteWithBodyWithResponse(ctx context.Context, organizationMember openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationMemberDeleteResponse, error)

	OrganizationMemberDeleteWithResponse(ctx context.Context, organizationMember openapi_types.UUID, body OrganizationMemberDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationMemberDeleteResponse, error)

	// OrganizationTenantDeleteWithResponse request
	OrganizationTenantDeleteWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationTenantDeleteResponse, error)

	// OrganizationTenantListApiTokensWithResponse request
	OrganizationTenantListApiTokensWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationTenantListApiTokensResponse, error)

	// OrganizationTenantCreateApiTokenWithBodyWithResponse request with any body
	OrganizationTenantCreateApiTokenWithBodyWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationTenantCreateApiTokenResponse, error)

	OrganizationTenantCreateApiTokenWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, body OrganizationTenantCreateApiTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationTenantCreateApiTokenResponse, error)

	// OrganizationTenantDeleteApiTokenWithResponse request
	OrganizationTenantDeleteApiTokenWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, apiToken openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationTenantDeleteApiTokenResponse, error)

	// OrganizationGetWithResponse request
	OrganizationGetWithResponse(ctx context.Context, organization openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationGetResponse, error)

	// OrganizationInviteListWithResponse request
	OrganizationInviteListWithResponse(ctx context.Context, organization openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationInviteListResponse, error)

	// OrganizationInviteCreateWithBodyWithResponse request with any body
	OrganizationInviteCreateWithBodyWithResponse(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationInviteCreateResponse, error)

	OrganizationInviteCreateWithResponse(ctx context.Context, organization openapi_types.UUID, body OrganizationInviteCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationInviteCreateResponse, error)

	// ManagementTokenCreateWithBodyWithResponse request with any body
	ManagementTokenCreateWithBodyWithResponse(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ManagementTokenCreateResponse, error)

	ManagementTokenCreateWithResponse(ctx context.Context, organization openapi_types.UUID, body ManagementTokenCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*ManagementTokenCreateResponse, error)

	// OrganizationCreateTenantWithBodyWithResponse request with any body
	OrganizationCreateTenantWithBodyWithResponse(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationCreateTenantResponse, error)

	OrganizationCreateTenantWithResponse(ctx context.Context, organization openapi_types.UUID, body OrganizationCreateTenantJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationCreateTenantResponse, error)
}

type OrganizationMemberDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *APIError
	JSON403      *APIError
}

// Status returns HTTPResponse.Status
func (r OrganizationMemberDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationMemberDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationTenantDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OrganizationTenant
	JSON400      *APIError
	JSON403      *APIError
}

// Status returns HTTPResponse.Status
func (r OrganizationTenantDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationTenantDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationTenantListApiTokensResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *APITokenList
	JSON400      *APIError
	JSON403      *APIError
}

// Status returns HTTPResponse.Status
func (r OrganizationTenantListApiTokensResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationTenantListApiTokensResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationTenantCreateApiTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *CreateTenantAPITokenResponse
	JSON400      *APIError
	JSON403      *APIError
}

// Status returns HTTPResponse.Status
func (r OrganizationTenantCreateApiTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationTenantCreateApiTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationTenantDeleteApiTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *APIError
	JSON403      *APIError
}

// Status returns HTTPResponse.Status
func (r OrganizationTenantDeleteApiTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationTenantDeleteApiTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Organization
	JSON400      *APIError
	JSON403      *APIError
}

// Status returns HTTPResponse.Status
func (r OrganizationGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationInviteListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OrganizationInviteList
	JSON400      *APIError
	JSON403      *APIError
}

// Status returns HTTPResponse.Status
func (r OrganizationInviteListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationInviteListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationInviteCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *APIError
	JSON403      *APIError
}

// Status returns HTTPResponse.Status
func (r OrganizationInviteCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationInviteCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ManagementTokenCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *CreateManagementTokenResponse
	JSON400      *APIError
	JSON403      *APIError
}

// Status returns HTTPResponse.Status
func (r ManagementTokenCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ManagementTokenCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationCreateTenantResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *OrganizationTenant
	JSON400      *APIError
	JSON403      *APIError
}

// Status returns HTTPResponse.Status
func (r OrganizationCreateTenantResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationCreateTenantResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// OrganizationMemberDeleteWithBodyWithResponse request with arbitrary body returning *OrganizationMemberDeleteResponse
func (c *ClientWithResponses) OrganizationMemberDeleteWithBodyWithResponse(ctx context.Context, organizationMember openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationMemberDeleteResponse, error) {
	rsp, err := c.OrganizationMemberDeleteWithBody(ctx, organizationMember, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationMemberDeleteResponse(rsp)
}

func (c *ClientWithResponses) OrganizationMemberDeleteWithResponse(ctx context.Context, organizationMember openapi_types.UUID, body OrganizationMemberDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationMemberDeleteResponse, error) {
	rsp, err := c.OrganizationMemberDelete(ctx, organizationMember, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationMemberDeleteResponse(rsp)
}

// OrganizationTenantDeleteWithResponse request returning *OrganizationTenantDeleteResponse
func (c *ClientWithResponses) OrganizationTenantDeleteWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationTenantDeleteResponse, error) {
	rsp, err := c.OrganizationTenantDelete(ctx, organizationTenant, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationTenantDeleteResponse(rsp)
}

// OrganizationTenantListApiTokensWithResponse request returning *OrganizationTenantListApiTokensResponse
func (c *ClientWithResponses) OrganizationTenantListApiTokensWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationTenantListApiTokensResponse, error) {
	rsp, err := c.OrganizationTenantListApiTokens(ctx, organizationTenant, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationTenantListApiTokensResponse(rsp)
}

// OrganizationTenantCreateApiTokenWithBodyWithResponse request with arbitrary body returning *OrganizationTenantCreateApiTokenResponse
func (c *ClientWithResponses) OrganizationTenantCreateApiTokenWithBodyWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationTenantCreateApiTokenResponse, error) {
	rsp, err := c.OrganizationTenantCreateApiTokenWithBody(ctx, organizationTenant, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationTenantCreateApiTokenResponse(rsp)
}

func (c *ClientWithResponses) OrganizationTenantCreateApiTokenWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, body OrganizationTenantCreateApiTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationTenantCreateApiTokenResponse, error) {
	rsp, err := c.OrganizationTenantCreateApiToken(ctx, organizationTenant, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationTenantCreateApiTokenResponse(rsp)
}

// OrganizationTenantDeleteApiTokenWithResponse request returning *OrganizationTenantDeleteApiTokenResponse
func (c *ClientWithResponses) OrganizationTenantDeleteApiTokenWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, apiToken openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationTenantDeleteApiTokenResponse, error) {
	rsp, err := c.OrganizationTenantDeleteApiToken(ctx, organizationTenant, apiToken, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationTenantDeleteApiTokenResponse(rsp)
}

// OrganizationGetWithResponse request returning *OrganizationGetResponse
func (c *ClientWithResponses) OrganizationGetWithResponse(ctx context.Context, organization openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationGetResponse, error) {
	rsp, err := c.OrganizationGet(ctx, organization, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationGetResponse(rsp)
}

// OrganizationInviteListWithResponse request returning *OrganizationInviteListResponse
func (c *ClientWithResponses) OrganizationInviteListWithResponse(ctx context.Context, organization openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationInviteListResponse, error) {
	rsp, err := c.OrganizationInviteList(ctx, organization, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationInviteListResponse(rsp)
}

// OrganizationInviteCreateWithBodyWithResponse request with arbitrary body returning *OrganizationInviteCreateResponse
func (c *ClientWithResponses) OrganizationInviteCreateWithBodyWithResponse(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationInviteCreateResponse, error) {
	rsp, err := c.OrganizationInviteCreateWithBody(ctx, organization, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationInviteCreateResponse(rsp)
}

func (c *ClientWithResponses) OrganizationInviteCreateWithResponse(ctx context.Context, organization openapi_types.UUID, body OrganizationInviteCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationInviteCreateResponse, error) {
	rsp, err := c.OrganizationInviteCreate(ctx, organization, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationInviteCreateResponse(rsp)
}

// ManagementTokenCreateWithBodyWithResponse request with arbitrary body returning *ManagementTokenCreateResponse
func (c *ClientWithResponses) ManagementTokenCreateWithBodyWithResponse(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ManagementTokenCreateResponse, error) {
	rsp, err := c.ManagementTokenCreateWithBody(ctx, organization, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseManagementTokenCreateResponse(rsp)
}

func (c *ClientWithResponses) ManagementTokenCreateWithResponse(ctx context.Context, organization openapi_types.UUID, body ManagementTokenCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*ManagementTokenCreateResponse, error) {
	rsp, err := c.ManagementTokenCreate(ctx, organization, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseManagementTokenCreateResponse(rsp)
}

// OrganizationCreateTenantWithBodyWithResponse request with arbitrary body returning *OrganizationCreateTenantResponse
func (c *ClientWithResponses) OrganizationCreateTenantWithBodyWithResponse(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationCreateTenantResponse, error) {
	rsp, err := c.OrganizationCreateTenantWithBody(ctx, organization, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationCreateTenantResponse(rsp)
}

func (c *ClientWithResponses) OrganizationCreateTenantWithResponse(ctx context.Context, organization openapi_types.UUID, body OrganizationCreateTenantJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationCreateTenantResponse, error) {
	rsp, err := c.OrganizationCreateTenant(ctx, organization, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationCreateTenantResponse(rsp)
}

// ParseOrganizationMemberDeleteResponse parses an HTTP response from a OrganizationMemberDeleteWithResponse call
func ParseOrganizationMemberDeleteResponse(rsp *http.Response) (*OrganizationMemberDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationMemberDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseOrganizationTenantDeleteResponse parses an HTTP response from a OrganizationTenantDeleteWithResponse call
func ParseOrganizationTenantDeleteResponse(rsp *http.Response) (*OrganizationTenantDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationTenantDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OrganizationTenant
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseOrganizationTenantListApiTokensResponse parses an HTTP response from a OrganizationTenantListApiTokensWithResponse call
func ParseOrganizationTenantListApiTokensResponse(rsp *http.Response) (*OrganizationTenantListApiTokensResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationTenantListApiTokensResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest APITokenList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseOrganizationTenantCreateApiTokenResponse parses an HTTP response from a OrganizationTenantCreateApiTokenWithResponse call
func ParseOrganizationTenantCreateApiTokenResponse(rsp *http.Response) (*OrganizationTenantCreateApiTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationTenantCreateApiTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CreateTenantAPITokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseOrganizationTenantDeleteApiTokenResponse parses an HTTP response from a OrganizationTenantDeleteApiTokenWithResponse call
func ParseOrganizationTenantDeleteApiTokenResponse(rsp *http.Response) (*OrganizationTenantDeleteApiTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationTenantDeleteApiTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseOrganizationGetResponse parses an HTTP response from a OrganizationGetWithResponse call
func ParseOrganizationGetResponse(rsp *http.Response) (*OrganizationGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Organization
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseOrganizationInviteListResponse parses an HTTP response from a OrganizationInviteListWithResponse call
func ParseOrganizationInviteListResponse(rsp *http.Response) (*OrganizationInviteListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationInviteListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OrganizationInviteList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseOrganizationInviteCreateResponse parses an HTTP response from a OrganizationInviteCreateWithResponse call
func ParseOrganizationInviteCreateResponse(rsp *http.Response) (*OrganizationInviteCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationInviteCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseManagementTokenCreateResponse parses an HTTP response from a ManagementTokenCreateWithResponse call
func ParseManagementTokenCreateResponse(rsp *http.Response) (*ManagementTokenCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ManagementTokenCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CreateManagementTokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseOrganizationCreateTenantResponse parses an HTTP response from a OrganizationCreateTenantWithResponse call
func ParseOrganizationCreateTenantResponse(rsp *http.Response) (*OrganizationCreateTenantResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationCreateTenantResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest OrganizationTenant
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}
