// Package managementclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package managementclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	externalRef0 "github.com/hatchet-dev/hatchet/api/v1/server/oas/gen"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CustomAuthScopes = "customAuth.Scopes"
)

// Defines values for OrganizationMemberType.
const (
	OWNER OrganizationMemberType = "OWNER"
)

// Defines values for TenantStatus.
const (
	Active   TenantStatus = "active"
	Archived TenantStatus = "archived"
)

// APIErrors defines model for APIErrors.
type APIErrors = externalRef0.APIErrors

// APIResourceMeta defines model for APIResourceMeta.
type APIResourceMeta = externalRef0.APIResourceMeta

// APITokenList defines model for APITokenList.
type APITokenList = externalRef0.ListAPITokensResponse

// AddOrganizationMembersRequest defines model for AddOrganizationMembersRequest.
type AddOrganizationMembersRequest struct {
	// Emails Array of user emails to add to the organization
	Emails []openapi_types.Email `json:"emails"`
}

// CreateNewTenantForOrganizationRequest defines model for CreateNewTenantForOrganizationRequest.
type CreateNewTenantForOrganizationRequest struct {
	// Name The name of the tenant.
	Name string `json:"name"`

	// Slug The slug of the tenant.
	Slug string `json:"slug"`
}

// CreateTenantAPITokenRequest defines model for CreateTenantAPITokenRequest.
type CreateTenantAPITokenRequest = externalRef0.CreateAPITokenRequest

// CreateTenantAPITokenResponse defines model for CreateTenantAPITokenResponse.
type CreateTenantAPITokenResponse = externalRef0.CreateAPITokenResponse

// DeleteOrganizationMembersRequest defines model for DeleteOrganizationMembersRequest.
type DeleteOrganizationMembersRequest struct {
	// Emails Array of user emails to remove from the organization
	Emails []openapi_types.Email `json:"emails"`
}

// Organization defines model for Organization.
type Organization struct {
	Members  []OrganizationMember `json:"members"`
	Metadata APIResourceMeta      `json:"metadata"`

	// Name Name of the organization
	Name string `json:"name"`

	// Slug Unique slug of the organization
	Slug    string               `json:"slug"`
	Tenants []OrganizationTenant `json:"tenants"`
}

// OrganizationMember defines model for OrganizationMember.
type OrganizationMember struct {
	MemberType OrganizationMemberType `json:"memberType"`
	Metadata   APIResourceMeta        `json:"metadata"`

	// UserId ID of the user
	UserId openapi_types.UUID `json:"userId"`
}

// OrganizationMemberList defines model for OrganizationMemberList.
type OrganizationMemberList struct {
	Pagination PaginationResponse   `json:"pagination"`
	Rows       []OrganizationMember `json:"rows"`
}

// OrganizationMemberType defines model for OrganizationMemberType.
type OrganizationMemberType string

// OrganizationTenant defines model for OrganizationTenant.
type OrganizationTenant struct {
	// ArchivedAt The timestamp at which the tenant was archived
	ArchivedAt *time.Time `json:"archivedAt,omitempty"`

	// Id ID of the tenant
	Id     openapi_types.UUID `json:"id"`
	Status TenantStatus       `json:"status"`
}

// PaginationResponse defines model for PaginationResponse.
type PaginationResponse = externalRef0.PaginationResponse

// TenantStatus defines model for TenantStatus.
type TenantStatus string

// OrganizationTenantCreateApiTokenJSONRequestBody defines body for OrganizationTenantCreateApiToken for application/json ContentType.
type OrganizationTenantCreateApiTokenJSONRequestBody = CreateTenantAPITokenRequest

// OrganizationUpdateMembersJSONRequestBody defines body for OrganizationUpdateMembers for application/json ContentType.
type OrganizationUpdateMembersJSONRequestBody = AddOrganizationMembersRequest

// OrganizationUpdateRemoveMembersJSONRequestBody defines body for OrganizationUpdateRemoveMembers for application/json ContentType.
type OrganizationUpdateRemoveMembersJSONRequestBody = DeleteOrganizationMembersRequest

// OrganizationCreateTenantJSONRequestBody defines body for OrganizationCreateTenant for application/json ContentType.
type OrganizationCreateTenantJSONRequestBody = CreateNewTenantForOrganizationRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// OrganizationTenantDelete request
	OrganizationTenantDelete(ctx context.Context, organizationTenant openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationTenantListApiTokens request
	OrganizationTenantListApiTokens(ctx context.Context, organizationTenant openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationTenantCreateApiTokenWithBody request with any body
	OrganizationTenantCreateApiTokenWithBody(ctx context.Context, organizationTenant openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	OrganizationTenantCreateApiToken(ctx context.Context, organizationTenant openapi_types.UUID, body OrganizationTenantCreateApiTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationTenantDeleteApiToken request
	OrganizationTenantDeleteApiToken(ctx context.Context, organizationTenant openapi_types.UUID, apiToken openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationGet request
	OrganizationGet(ctx context.Context, organization openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationListMembers request
	OrganizationListMembers(ctx context.Context, organization openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationUpdateMembersWithBody request with any body
	OrganizationUpdateMembersWithBody(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	OrganizationUpdateMembers(ctx context.Context, organization openapi_types.UUID, body OrganizationUpdateMembersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationUpdateRemoveMembersWithBody request with any body
	OrganizationUpdateRemoveMembersWithBody(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	OrganizationUpdateRemoveMembers(ctx context.Context, organization openapi_types.UUID, body OrganizationUpdateRemoveMembersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationCreateTenantWithBody request with any body
	OrganizationCreateTenantWithBody(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	OrganizationCreateTenant(ctx context.Context, organization openapi_types.UUID, body OrganizationCreateTenantJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) OrganizationTenantDelete(ctx context.Context, organizationTenant openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationTenantDeleteRequest(c.Server, organizationTenant)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationTenantListApiTokens(ctx context.Context, organizationTenant openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationTenantListApiTokensRequest(c.Server, organizationTenant)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationTenantCreateApiTokenWithBody(ctx context.Context, organizationTenant openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationTenantCreateApiTokenRequestWithBody(c.Server, organizationTenant, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationTenantCreateApiToken(ctx context.Context, organizationTenant openapi_types.UUID, body OrganizationTenantCreateApiTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationTenantCreateApiTokenRequest(c.Server, organizationTenant, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationTenantDeleteApiToken(ctx context.Context, organizationTenant openapi_types.UUID, apiToken openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationTenantDeleteApiTokenRequest(c.Server, organizationTenant, apiToken)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationGet(ctx context.Context, organization openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationGetRequest(c.Server, organization)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationListMembers(ctx context.Context, organization openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationListMembersRequest(c.Server, organization)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationUpdateMembersWithBody(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationUpdateMembersRequestWithBody(c.Server, organization, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationUpdateMembers(ctx context.Context, organization openapi_types.UUID, body OrganizationUpdateMembersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationUpdateMembersRequest(c.Server, organization, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationUpdateRemoveMembersWithBody(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationUpdateRemoveMembersRequestWithBody(c.Server, organization, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationUpdateRemoveMembers(ctx context.Context, organization openapi_types.UUID, body OrganizationUpdateRemoveMembersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationUpdateRemoveMembersRequest(c.Server, organization, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationCreateTenantWithBody(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationCreateTenantRequestWithBody(c.Server, organization, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationCreateTenant(ctx context.Context, organization openapi_types.UUID, body OrganizationCreateTenantJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationCreateTenantRequest(c.Server, organization, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewOrganizationTenantDeleteRequest generates requests for OrganizationTenantDelete
func NewOrganizationTenantDeleteRequest(server string, organizationTenant openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization-tenant", runtime.ParamLocationPath, organizationTenant)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organization-tenants/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOrganizationTenantListApiTokensRequest generates requests for OrganizationTenantListApiTokens
func NewOrganizationTenantListApiTokensRequest(server string, organizationTenant openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization-tenant", runtime.ParamLocationPath, organizationTenant)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organization-tenants/%s/api-tokens", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOrganizationTenantCreateApiTokenRequest calls the generic OrganizationTenantCreateApiToken builder with application/json body
func NewOrganizationTenantCreateApiTokenRequest(server string, organizationTenant openapi_types.UUID, body OrganizationTenantCreateApiTokenJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewOrganizationTenantCreateApiTokenRequestWithBody(server, organizationTenant, "application/json", bodyReader)
}

// NewOrganizationTenantCreateApiTokenRequestWithBody generates requests for OrganizationTenantCreateApiToken with any type of body
func NewOrganizationTenantCreateApiTokenRequestWithBody(server string, organizationTenant openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization-tenant", runtime.ParamLocationPath, organizationTenant)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organization-tenants/%s/api-tokens", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewOrganizationTenantDeleteApiTokenRequest generates requests for OrganizationTenantDeleteApiToken
func NewOrganizationTenantDeleteApiTokenRequest(server string, organizationTenant openapi_types.UUID, apiToken openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization-tenant", runtime.ParamLocationPath, organizationTenant)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "api-token", runtime.ParamLocationPath, apiToken)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organization-tenants/%s/api-tokens/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOrganizationGetRequest generates requests for OrganizationGet
func NewOrganizationGetRequest(server string, organization openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization", runtime.ParamLocationPath, organization)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organizations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOrganizationListMembersRequest generates requests for OrganizationListMembers
func NewOrganizationListMembersRequest(server string, organization openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization", runtime.ParamLocationPath, organization)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organizations/%s/members", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOrganizationUpdateMembersRequest calls the generic OrganizationUpdateMembers builder with application/json body
func NewOrganizationUpdateMembersRequest(server string, organization openapi_types.UUID, body OrganizationUpdateMembersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewOrganizationUpdateMembersRequestWithBody(server, organization, "application/json", bodyReader)
}

// NewOrganizationUpdateMembersRequestWithBody generates requests for OrganizationUpdateMembers with any type of body
func NewOrganizationUpdateMembersRequestWithBody(server string, organization openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization", runtime.ParamLocationPath, organization)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organizations/%s/members", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewOrganizationUpdateRemoveMembersRequest calls the generic OrganizationUpdateRemoveMembers builder with application/json body
func NewOrganizationUpdateRemoveMembersRequest(server string, organization openapi_types.UUID, body OrganizationUpdateRemoveMembersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewOrganizationUpdateRemoveMembersRequestWithBody(server, organization, "application/json", bodyReader)
}

// NewOrganizationUpdateRemoveMembersRequestWithBody generates requests for OrganizationUpdateRemoveMembers with any type of body
func NewOrganizationUpdateRemoveMembersRequestWithBody(server string, organization openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization", runtime.ParamLocationPath, organization)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organizations/%s/remove-members", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewOrganizationCreateTenantRequest calls the generic OrganizationCreateTenant builder with application/json body
func NewOrganizationCreateTenantRequest(server string, organization openapi_types.UUID, body OrganizationCreateTenantJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewOrganizationCreateTenantRequestWithBody(server, organization, "application/json", bodyReader)
}

// NewOrganizationCreateTenantRequestWithBody generates requests for OrganizationCreateTenant with any type of body
func NewOrganizationCreateTenantRequestWithBody(server string, organization openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "organization", runtime.ParamLocationPath, organization)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/management/organizations/%s/tenants", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// OrganizationTenantDeleteWithResponse request
	OrganizationTenantDeleteWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationTenantDeleteResponse, error)

	// OrganizationTenantListApiTokensWithResponse request
	OrganizationTenantListApiTokensWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationTenantListApiTokensResponse, error)

	// OrganizationTenantCreateApiTokenWithBodyWithResponse request with any body
	OrganizationTenantCreateApiTokenWithBodyWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationTenantCreateApiTokenResponse, error)

	OrganizationTenantCreateApiTokenWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, body OrganizationTenantCreateApiTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationTenantCreateApiTokenResponse, error)

	// OrganizationTenantDeleteApiTokenWithResponse request
	OrganizationTenantDeleteApiTokenWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, apiToken openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationTenantDeleteApiTokenResponse, error)

	// OrganizationGetWithResponse request
	OrganizationGetWithResponse(ctx context.Context, organization openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationGetResponse, error)

	// OrganizationListMembersWithResponse request
	OrganizationListMembersWithResponse(ctx context.Context, organization openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationListMembersResponse, error)

	// OrganizationUpdateMembersWithBodyWithResponse request with any body
	OrganizationUpdateMembersWithBodyWithResponse(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationUpdateMembersResponse, error)

	OrganizationUpdateMembersWithResponse(ctx context.Context, organization openapi_types.UUID, body OrganizationUpdateMembersJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationUpdateMembersResponse, error)

	// OrganizationUpdateRemoveMembersWithBodyWithResponse request with any body
	OrganizationUpdateRemoveMembersWithBodyWithResponse(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationUpdateRemoveMembersResponse, error)

	OrganizationUpdateRemoveMembersWithResponse(ctx context.Context, organization openapi_types.UUID, body OrganizationUpdateRemoveMembersJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationUpdateRemoveMembersResponse, error)

	// OrganizationCreateTenantWithBodyWithResponse request with any body
	OrganizationCreateTenantWithBodyWithResponse(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationCreateTenantResponse, error)

	OrganizationCreateTenantWithResponse(ctx context.Context, organization openapi_types.UUID, body OrganizationCreateTenantJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationCreateTenantResponse, error)
}

type OrganizationTenantDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OrganizationTenant
	JSON400      *APIErrors
	JSON403      *APIErrors
}

// Status returns HTTPResponse.Status
func (r OrganizationTenantDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationTenantDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationTenantListApiTokensResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *APITokenList
	JSON400      *APIErrors
	JSON403      *APIErrors
}

// Status returns HTTPResponse.Status
func (r OrganizationTenantListApiTokensResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationTenantListApiTokensResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationTenantCreateApiTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *CreateTenantAPITokenResponse
	JSON400      *APIErrors
	JSON403      *APIErrors
}

// Status returns HTTPResponse.Status
func (r OrganizationTenantCreateApiTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationTenantCreateApiTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationTenantDeleteApiTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *APIErrors
	JSON403      *APIErrors
}

// Status returns HTTPResponse.Status
func (r OrganizationTenantDeleteApiTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationTenantDeleteApiTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Organization
	JSON400      *APIErrors
	JSON403      *APIErrors
}

// Status returns HTTPResponse.Status
func (r OrganizationGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationListMembersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OrganizationMemberList
	JSON400      *APIErrors
	JSON403      *APIErrors
}

// Status returns HTTPResponse.Status
func (r OrganizationListMembersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationListMembersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationUpdateMembersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *OrganizationMemberList
	JSON400      *APIErrors
	JSON403      *APIErrors
	JSON409      *APIErrors
}

// Status returns HTTPResponse.Status
func (r OrganizationUpdateMembersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationUpdateMembersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationUpdateRemoveMembersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *APIErrors
	JSON403      *APIErrors
}

// Status returns HTTPResponse.Status
func (r OrganizationUpdateRemoveMembersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationUpdateRemoveMembersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationCreateTenantResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *OrganizationTenant
	JSON400      *APIErrors
	JSON403      *APIErrors
}

// Status returns HTTPResponse.Status
func (r OrganizationCreateTenantResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationCreateTenantResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// OrganizationTenantDeleteWithResponse request returning *OrganizationTenantDeleteResponse
func (c *ClientWithResponses) OrganizationTenantDeleteWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationTenantDeleteResponse, error) {
	rsp, err := c.OrganizationTenantDelete(ctx, organizationTenant, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationTenantDeleteResponse(rsp)
}

// OrganizationTenantListApiTokensWithResponse request returning *OrganizationTenantListApiTokensResponse
func (c *ClientWithResponses) OrganizationTenantListApiTokensWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationTenantListApiTokensResponse, error) {
	rsp, err := c.OrganizationTenantListApiTokens(ctx, organizationTenant, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationTenantListApiTokensResponse(rsp)
}

// OrganizationTenantCreateApiTokenWithBodyWithResponse request with arbitrary body returning *OrganizationTenantCreateApiTokenResponse
func (c *ClientWithResponses) OrganizationTenantCreateApiTokenWithBodyWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationTenantCreateApiTokenResponse, error) {
	rsp, err := c.OrganizationTenantCreateApiTokenWithBody(ctx, organizationTenant, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationTenantCreateApiTokenResponse(rsp)
}

func (c *ClientWithResponses) OrganizationTenantCreateApiTokenWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, body OrganizationTenantCreateApiTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationTenantCreateApiTokenResponse, error) {
	rsp, err := c.OrganizationTenantCreateApiToken(ctx, organizationTenant, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationTenantCreateApiTokenResponse(rsp)
}

// OrganizationTenantDeleteApiTokenWithResponse request returning *OrganizationTenantDeleteApiTokenResponse
func (c *ClientWithResponses) OrganizationTenantDeleteApiTokenWithResponse(ctx context.Context, organizationTenant openapi_types.UUID, apiToken openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationTenantDeleteApiTokenResponse, error) {
	rsp, err := c.OrganizationTenantDeleteApiToken(ctx, organizationTenant, apiToken, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationTenantDeleteApiTokenResponse(rsp)
}

// OrganizationGetWithResponse request returning *OrganizationGetResponse
func (c *ClientWithResponses) OrganizationGetWithResponse(ctx context.Context, organization openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationGetResponse, error) {
	rsp, err := c.OrganizationGet(ctx, organization, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationGetResponse(rsp)
}

// OrganizationListMembersWithResponse request returning *OrganizationListMembersResponse
func (c *ClientWithResponses) OrganizationListMembersWithResponse(ctx context.Context, organization openapi_types.UUID, reqEditors ...RequestEditorFn) (*OrganizationListMembersResponse, error) {
	rsp, err := c.OrganizationListMembers(ctx, organization, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationListMembersResponse(rsp)
}

// OrganizationUpdateMembersWithBodyWithResponse request with arbitrary body returning *OrganizationUpdateMembersResponse
func (c *ClientWithResponses) OrganizationUpdateMembersWithBodyWithResponse(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationUpdateMembersResponse, error) {
	rsp, err := c.OrganizationUpdateMembersWithBody(ctx, organization, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationUpdateMembersResponse(rsp)
}

func (c *ClientWithResponses) OrganizationUpdateMembersWithResponse(ctx context.Context, organization openapi_types.UUID, body OrganizationUpdateMembersJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationUpdateMembersResponse, error) {
	rsp, err := c.OrganizationUpdateMembers(ctx, organization, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationUpdateMembersResponse(rsp)
}

// OrganizationUpdateRemoveMembersWithBodyWithResponse request with arbitrary body returning *OrganizationUpdateRemoveMembersResponse
func (c *ClientWithResponses) OrganizationUpdateRemoveMembersWithBodyWithResponse(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationUpdateRemoveMembersResponse, error) {
	rsp, err := c.OrganizationUpdateRemoveMembersWithBody(ctx, organization, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationUpdateRemoveMembersResponse(rsp)
}

func (c *ClientWithResponses) OrganizationUpdateRemoveMembersWithResponse(ctx context.Context, organization openapi_types.UUID, body OrganizationUpdateRemoveMembersJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationUpdateRemoveMembersResponse, error) {
	rsp, err := c.OrganizationUpdateRemoveMembers(ctx, organization, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationUpdateRemoveMembersResponse(rsp)
}

// OrganizationCreateTenantWithBodyWithResponse request with arbitrary body returning *OrganizationCreateTenantResponse
func (c *ClientWithResponses) OrganizationCreateTenantWithBodyWithResponse(ctx context.Context, organization openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationCreateTenantResponse, error) {
	rsp, err := c.OrganizationCreateTenantWithBody(ctx, organization, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationCreateTenantResponse(rsp)
}

func (c *ClientWithResponses) OrganizationCreateTenantWithResponse(ctx context.Context, organization openapi_types.UUID, body OrganizationCreateTenantJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationCreateTenantResponse, error) {
	rsp, err := c.OrganizationCreateTenant(ctx, organization, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationCreateTenantResponse(rsp)
}

// ParseOrganizationTenantDeleteResponse parses an HTTP response from a OrganizationTenantDeleteWithResponse call
func ParseOrganizationTenantDeleteResponse(rsp *http.Response) (*OrganizationTenantDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationTenantDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OrganizationTenant
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseOrganizationTenantListApiTokensResponse parses an HTTP response from a OrganizationTenantListApiTokensWithResponse call
func ParseOrganizationTenantListApiTokensResponse(rsp *http.Response) (*OrganizationTenantListApiTokensResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationTenantListApiTokensResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest APITokenList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseOrganizationTenantCreateApiTokenResponse parses an HTTP response from a OrganizationTenantCreateApiTokenWithResponse call
func ParseOrganizationTenantCreateApiTokenResponse(rsp *http.Response) (*OrganizationTenantCreateApiTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationTenantCreateApiTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CreateTenantAPITokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseOrganizationTenantDeleteApiTokenResponse parses an HTTP response from a OrganizationTenantDeleteApiTokenWithResponse call
func ParseOrganizationTenantDeleteApiTokenResponse(rsp *http.Response) (*OrganizationTenantDeleteApiTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationTenantDeleteApiTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseOrganizationGetResponse parses an HTTP response from a OrganizationGetWithResponse call
func ParseOrganizationGetResponse(rsp *http.Response) (*OrganizationGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Organization
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseOrganizationListMembersResponse parses an HTTP response from a OrganizationListMembersWithResponse call
func ParseOrganizationListMembersResponse(rsp *http.Response) (*OrganizationListMembersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationListMembersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OrganizationMemberList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseOrganizationUpdateMembersResponse parses an HTTP response from a OrganizationUpdateMembersWithResponse call
func ParseOrganizationUpdateMembersResponse(rsp *http.Response) (*OrganizationUpdateMembersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationUpdateMembersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest OrganizationMemberList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseOrganizationUpdateRemoveMembersResponse parses an HTTP response from a OrganizationUpdateRemoveMembersWithResponse call
func ParseOrganizationUpdateRemoveMembersResponse(rsp *http.Response) (*OrganizationUpdateRemoveMembersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationUpdateRemoveMembersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseOrganizationCreateTenantResponse parses an HTTP response from a OrganizationCreateTenantWithResponse call
func ParseOrganizationCreateTenantResponse(rsp *http.Response) (*OrganizationCreateTenantResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationCreateTenantResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest OrganizationTenant
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIErrors
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}
